Repository testing-library/testing-playground, pull requests merged in 2020-06, with the labels that each got.

#73 chore: move state management to context
  src/components/App.js
  src/components/Context.js
  src/components/Editor.js
  src/components/Embedded.js
  src/components/MarkupEditor.js
  src/components/Playground.js
  src/components/Preview.js
  src/components/Query.js
  src/components/QueryEditor.js
  src/components/Result.js
  src/components/ResultQueries.js
  src/components/ResultSuggestion.js
  src/constants.js
  src/hooks/usePlayground.js
  src/plugin.js
  tests/utils/render.js
Labels: chore

#74 feat: render placeholder image when no markup is provided
  public/code_thinking.png
  src/components/AddHtml.js
  src/components/Preview.js
  src/components/Result.js
Labels: feature

#100 fix: blank initial state
  src/components/Context.js
Labels: bug

#96 chore: upgrade parcel to v2 (alpha)
  .babelrc
  .gitignore
  .parcelrc
  package-lock.json
  package.json
  postcss.config.js
  src/components/AddHtml.js
  src/components/Header.js
  src/index.html
  src/styles/index.css
Labels: chore, dependencies

#98 chore: import `@testing-library/dom` from npm instead of unpkg
  package-lock.json
  package.json
  src/components/Editor.js
  src/index.html
  src/parser.js
  tests/setupTests.js
Labels: chore, dependencies

#103 chore: improve state management and reduce re-renders
  src/components/Embedded.js
  src/components/MarkupEditor.js
  src/components/Playground.js
  src/components/Playground.test.js
  src/components/Preview.js
  src/components/PreviewHint.js
  src/components/Query.js
  src/components/QueryEditor.js
  src/components/QueryOutput.js
  src/components/Result.js
  src/components/ResultQueries.js
  src/components/ResultSuggestion.js
  src/hooks/usePlayground.js
  src/lib/deepEqual.js
  src/lib/queryAdvise.js
  src/parser.js
  src/plugin.html
  src/plugin.js
  tests/utils/render.js
Labels: chore

#119 chore: use 🧪 as logo/mascot
  .gitignore
  README.md
  docs/icon.png
  package.json
  public/114-production.png
  public/120-production.png
  public/144-production.png
  public/150-production.png
  public/152-production.png
  public/16-production.png
  public/180-production.png
  public/192-production.png
  public/310-production.png
  public/32-production.png
  public/36-production.png
  public/48-production.png
  public/57-production.png
  public/60-production.png
  public/70-production.png
  public/72-production.png
  public/76-production.png
  public/96-production.png
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/browserconfig.xml
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/icon.png
  public/site.webmanifest
  src/components/Header.js
  src/index.html
Labels: chore

#121 fix: bug setting query to wrong prop in state
  src/hooks/usePlayground.js
Labels: bug

#120 chore: add state logger to improve developer experience
  package-lock.json
  package.json
  src/hooks/usePlayground.js
  src/lib/logger.js
Labels: chore

#122 docs: update readme
  ROADMAP.md
  docs/testing-playground-com.gif
Labels: documentation

#131 docs: add CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#132 docs: add MAINTAINING.md
  MAINTAINING.md
Labels: documentation

#139 chore: add build scripts
  package-lock.json
  package.json
  public/site.webmanifest
  scripts/build-client.js
  scripts/build-lambda.js
  scripts/build.js
  src/index.html
  src/lambda/oembed/oembed.js
  src/lib/logger.js
  workbox-config.js
Labels: chore

#165 chore: add issue templates
  .github/ISSUE_TEMPLATE/1.bug.md
  .github/ISSUE_TEMPLATE/2.feature.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: chore

#169 chore: change logger settings
  src/lib/logger.js
Labels: chore

#174 fix: restore auto indent size in markup editor
  src/components/Editor.js
Labels: bug

#167 feat: add event-debugging environment
  package-lock.json
  package.json
  src/components/App.js
  src/components/DomEvents.js
  src/components/IconButton.js
  src/components/Layout.js
  src/components/Preview.js
  src/components/Scrollable.js
  src/components/TrashcanIcon.js
  src/hooks/usePlayground.js
  src/images/EmptyStreetImg.js
Labels: feature

#150 fix: use @testing-library/dom native methods for suggestion btns
  devtools/src/devtools/components/MenuBar.js
  package-lock.json
  package.json
  src/components/Result.js
  src/components/ResultQueries.js
  src/constants.js
  src/lib/getExpression.js
  src/lib/getFieldName.js
  src/lib/index.js
  src/lib/queryAdvise.js
  src/lib/queryAdvise.test.js
  src/parser.js
Labels: bug

#186 chore: add rule for eslint curly braces && lint them all
  .babelrc
  .eslintrc.js
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .lintstagedrc.js
  CODE_OF_CONDUCT.md
  MAINTAINING.md
  README.md
  devtools/src/devtools/main.html
  devtools/src/devtools/pane.html
  devtools/src/devtools/panel.html
  devtools/src/manifest.json
  src/components/Editor.js
  src/embed.html
  src/styles/app.pcss
  src/styles/codemirror.pcss
Labels: chore

#168 feat: improve styles in preview pane
  src/styles/app.pcss
Labels: feature

#178 feat: reverse order of event log entries
  src/components/DomEvents.js
  src/components/StickyList.js
Labels: feature

#188 chore: add eslint config for react hooks
  .eslintrc.js
  package-lock.json
  package.json
Labels: chore

#197 feat: format editor content on blur
  src/components/Editor.js
  src/lib/beautify.js
  src/lib/state.js
Labels: feature

#199 feat: format editor content on paste
  src/components/Editor.js
  src/lib/beautify.js
  src/lib/state.js
Labels: feature

#181 feat: add result suggestion to scrollable area for small screen support
  src/components/Result.js
Labels: feature

#198 feat: add "snapshot" function for wrapper elements
  src/components/Expandable.js
  src/components/PreviewHint.js
  src/lib/queryAdvise.js
  src/styles/app.pcss
Labels: feature

#193 chore: fix tailwind hot reload
  postcss.config.js
Labels: bug, developer-experience

#194 feat: add copy to clipboard button for DomEvents
  src/components/CopyButton.js
  src/components/CopyButton.test.js
  src/components/DomEvents.js
  src/components/IconButton.js
  src/components/ResultCopyButton.js
  src/components/ResultCopyButton.test.js
  src/components/ResultSuggestion.js
  src/components/icons/CopyIcon.js
  src/components/icons/SuccessIcon.js
  src/components/icons/TrashcanIcon.js
Labels: feature

#210 fix: bug causing WSOD on initial render
  src/components/ResultQueries.js
Labels: bug

#208 chore: add option to disable diffing
  package.json
  src/lib/logger.js
Labels: chore

#209 feat: add support for `user-event`
  devtools/src/content-script/highlighter/Overlay.js
  devtools/src/content-script/highlighter/index.js
  devtools/src/content-script/highlighter/utils.js
  devtools/src/devtools/panel.js
  package-lock.json
  package.json
  scripts/build-client.js
  src/components/CopyButton.js
  src/components/DomEvents.js
  src/components/Editor.js
  src/components/EmptyPane.js
  src/components/Expandable.js
  src/components/MarkupEditor.js
  src/components/Playground.js
  src/components/Preview.js
  src/components/PreviewHint.js
  src/components/Query.js
  src/components/QueryEditor.js
  src/components/Result.js
  src/components/Result.test.js
  src/components/ResultQueries.js
  src/components/Scrollable.js
  src/components/Spinner.js
  src/components/icons/CopyIcon.js
  src/components/icons/SuccessIcon.js
  src/components/icons/TrashcanIcon.js
  src/constants.js
  src/hooks/usePlayground.js
  src/lib/postMessage.js
  src/lib/queryAdvise.js
  src/parser.js
  src/sandbox.html
  src/sandbox.js
  src/styles/app.pcss
  src/styles/index.css
  src/styles/spinner.pcss
Labels: feature

#195 feat: add sorter for DomEvents
  devtools/src/manifest.json
  package-lock.json
  package.json
  src/components/DomEvents.js
  src/components/StickyList.js
  src/hooks/useSorter.js
  src/hooks/useSorter.test.js
Labels: feature
