Repository testing-library/testing-playground, pull requests merged in 2020-10, with the labels that each got.

#276 fix: restore support for state-full urls
  src/hooks/usePlayground.js
  src/lib/state/url.js
Labels: bug

#277 feat: support saving with partial content
  src/lambda/gist/gist.js
Labels: feature

#279 chore: update github actions
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: chore

#278 feat: auto save on share
  src/components/Header.js
  src/components/Share.js
  src/hooks/usePlayground.js
Labels: feature

#280 chore: rename issue tracker link to GitHub
  src/components/Header.js
Labels: chore

#281 chore: add update button to embed demo
  src/embed.html
Labels: chore

#285 fix: correct oembed frame source
  src/lambda/oembed/oembed.js
  src/lambda/server/server.js
Labels: bug

#286 feat: improve embed experience
  src/components/Embed.js
  src/components/Embedded.js
  src/components/Header.js
  src/components/Share.js
  src/lambda/oembed/oembed.js
  src/lambda/server/server.js
Labels: feature

#289 feat: change default panes for embed mode to query,preview
  src/components/Embedded.js
Labels: feature

#290 feat: add url validation to oembed
  src/lambda/oembed/oembed.js
  src/lambda/server/server.js
Labels: feature

#292 fix: bring embed panes in line with the embed in the GUI
  src/components/Embed.js
  src/components/Embedded.js
  src/constants.js
  src/lambda/oembed/oembed.js
Labels: bug

#293 revert: use global URL instead of import (#291)
  package.json
  src/lambda/oembed/oembed.js
Labels: bug
